################################## README BEFORE USAGE ##################################

# Write your paths relative to any of the following directories (which to they belong):

#     * metadata: ./{proj_metadata_dir}
#     * data: ./{proj_data_dir}
#     * ref: ./{proj_ref_dir}
#     * figures: ./{proj_figures_dir}
#     * projects (mn5): ./{projects_dir}
#     * scratch (mn5): ./{scratch_dir}
#     * data (mn5): ./{data_dir}


# For any other *_dir path you named in resources.yml "setup_settings", you can
#  also refer to this here:
#     * something_random: ./{something_random_dir}

#

############ --------------------------------------------------------------- ############

# metadata (adapt it if you modify the name of metadata, so snakefiles can parse the samples)
metadata: ./{proj_metadata_dir}/metadata.tsv

# example
data:
  sam: ./{proj_data_dir}/fake_dir/example.sam
  bam: ./{proj_data_dir}/fake_dir/example.bam
  sorted_sam: ./{proj_data_dir}/fake_dir/example_sorted.sam
