################################## README BEFORE USAGE ##################################

# Write your paths relative to any of the following directories (which to they belong):

#     -metadata: \{metadata_dir\}/
#     -data: \{data_dir\}/
#     -ref: \{ref_dir\}/
#     -figures: \{figures_dir\}/

############ --------------------------------------------------------------- ############

# metadata (adapt it if you modify the name of metadata, so snakefiles can parse the samples)
metadata: \{metadata_dir\}/metadata.tsv

# example
example:
  sam: \{data_dir\}/fake_dir/example_{sample}_{replicate}.sam
  bam: \{data_dir\}/fake_dir/example_{sample}.bam
  sorted_sam: \{data_dir\}/fake_dir/example_{sample}_sorted.sam
